### PR TITLE
fix #64, allow more control over time labels

### LINKED ISSUE #64: provide more control over the format of time labels on the axis
```
In some cases it would be useful to have more control over the time labels. 
There is currently a way to set the format string, but I cannot specify a 
different format for significant boundaries like day, month, or year 
transitions. Also, it has a lot of other parameters which make it difficult to 
use. I attached some example images showing the intent.

Another example from d3 library docs:

http://bl.ocks.org/mbostock/4149176

This patch has a quick version:

https://github.com/brharrington/rrd4j/commit/42e2b74d78207230f8bbd817e57f5ab1374
36b09


```

Original issue reported on code.google.com by `brharrin...@gmail.com` on 22 Feb 2014 at 9:39

Attachments:
* [demo.days.gif](https://storage.googleapis.com/google-code-attachments/rrd4j/issue-64/comment-0/demo.days.gif)
* [demo.month.gif](https://storage.googleapis.com/google-code-attachments/rrd4j/issue-64/comment-0/demo.month.gif)
* [demo.year.gif](https://storage.googleapis.com/google-code-attachments/rrd4j/issue-64/comment-0/demo.year.gif)

### PR DESCRIPTION
**Pull request by brharrington**
Same as the patch from that ticket with some javadocs added
and a unit test for SimpleTimeLabelFormat.

### CODE REVIEW

**Comment by analytically** [comment]
@fbacchella

**Comment by fbacchella** [comment]
I will have a look at it.

**Comment by analytically** [comment]
Any luck?

**Comment by fbacchella** [comment]
yes, but I still not manage to get time to have a look.

**Comment by fbacchella** [comment]
I created the branch brharrington-time-labels, and made some improvement, can you tell me if it works for you ?
For complete test, I need to dig more in org.easymock.EasyMock, like it's used in org.rrd4j.graph.ValueAxisTest.

**Comment by brharrington** [comment]
Those changes look fine.

**Comment by fbacchella** [comment]
merged as 5301c29c9f2931e38f9d5ac98aba9f10239b8882

**Pull request closed without merging**
