### PR TITLE
Add OSGiSmokeTest using pax-exam

### PR DESCRIPTION
**Pull request by rombert**

### CODE REVIEW

**Comment by rombert** [comment]
The jdk11 build failed, but it does not seem to be related to my changes ...

> [ERROR] SonarQube server [http://localhost:9000] can not be reached

**Comment by rombert** [comment]
Thanks a lot of merging this! For my own planning, do you have plans to release a new version in the near future?

**Comment by fbacchella** [comment]
I will try to find time about that. Meanwhile you can play with it at [snaphot repo](https://oss.sonatype.org/content/repositories/snapshots/org/rrd4j/rrd4j/)

I imagine you've done this PR on purpose. Can you explain it (just for curiosity).

**Comment by rombert** [comment]
> I will try to find time about that. Meanwhile you can play with it at snaphot repo

Ack. thanks.

> I imagine you've done this PR on purpose. Can you explain it (just for curiosity).

Yup, it was on purpose. I'm playing around with a temperature monitoring system for my home. I wanted an easy way of storing data and graphing it. I knew about rrdtool and also about rr4dj from one of the projects I work with ( see https://github.com/apache/sling-org-apache-sling-commons-metrics-rrd4j ) so I tried to use that. Since I'm using OSGi for practically all backend development I thought it made sense to also add basic support for rrd4j so that others can benefit as well. The alternative was to 'wrap' rrd4j in a different bundle, but I prefer to upstream the OSGi support if at all possibe.

**Pull request merged**
