### PR TITLE
Added tests for org.rrd4j.core.Util

### PR DESCRIPTION
**Pull request by freddytuxworth**
Hi,

I've analysed your code base and noticed that there are no unit tests for the `org.rrd4j.core.Util` class. I've written some tests with the help of [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/products).

Hopefully these tests should help you detect any regressions caused by future code changes. If you'd like any more tests written for other classes, just let me know and I'd be happy to help.

### CODE REVIEW

**Comment by fbacchella** [comment]
That's nice thanks. But the missing tests are hard to do because, it should check for image generation.

**Comment by freddytuxworth** [comment]
Are you happy with these tests, or would you like something changed?

**Comment by fbacchella** [comment]
I made a comment about the useless final.

**Comment by fbacchella** [comment]
I merged it manually and removed all the useless final.

**Comment by freddytuxworth** [comment]
Thanks. Sorry, I couldn't find any comment, and wasn't sure what you meant, but now it makes sense. I hope the tests are useful.

**Pull request closed without merging**
